project_id = "bghxiqlldjmhniucrxqh"

[functions.generate-script]
verify_jwt = true

[functions.check-limits]
verify_jwt = false

[functions.generate-video]
verify_jwt = true

[functions.check-video-status]
verify_jwt = true

[functions.youtube-auth]
verify_jwt = false

[functions.youtube-upload]
verify_jwt = true

[functions.voice-preview]
verify_jwt = false
